### PR TITLE
Explain how to build with plain ghc(js) or cabal

### PR DESCRIPTION
**Pull request by mostalive**
Hi @ryantrinkle , Following up on my question from yesterday, turned your answer into a bit of documentation, with ghc(js) command modified to put (intermediate) compiler output outside src. I didn't use ghc without cabal or stack much before this.

I erred on the side of verbosity, I find as a reader some duplication with variations can be helpful in understanding how things work.

### CODE REVIEW

**Comment by mostalive** [comment]
Closed after 3 years of no activity.

**Comment by ryantrinkle** [comment]
@mostalive Hi, wow, sorry for missing this for so long!  I hope you don't mind me merging it now.

**Comment by ryantrinkle** [comment]
@mostalive I really appreciate you putting this together, and I've updated it now for the changes that have happened in the intervening time.

I don't know why this doesn't show as "merged" on github, but the git history does show this being merged from your repo.

**Comment by mostalive** [comment]
@ryantrinkle I guess githubs' eventual consistency has a long definition of
consistent ;-). Thanks for updating and merging!

**Pull request closed without merging**
